-- DROP TABLE IF EXISTS `T_SYS_CAR_MODEL`;

CREATE TABLE `T_SYS_CAR_MODEL` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `BRAND_ID` varchar(100) NOT NULL COMMENT '品牌ID',
  `BRAND_NAME` varchar(200) NOT NULL COMMENT '品牌名',
  `DISPLACEMENT` varchar(10) DEFAULT NULL COMMENT '排量',
  `GUIDE_PRICE` varchar(20) DEFAULT NULL COMMENT '指导价',
  `MODEL_ID` varchar(100) NOT NULL COMMENT '型号ID',
  `MODEL_NAME` varchar(200) NOT NULL COMMENT '型号名',
  `PRODUCTION_STATE` varchar(10) DEFAULT NULL COMMENT '生产状态（在产、停产）',
  `PRODUCTION_WAY` varchar(10) DEFAULT NULL COMMENT '生产方式（国产、合资、进口）',
  `SALE_VERSION` varchar(100) DEFAULT NULL COMMENT '销售版本',
  `SALE_YEAR` varchar(10) DEFAULT NULL COMMENT '销售年份',
  `SERISE_ID` varchar(100) NOT NULL COMMENT '系列ID',
  `SERISE_NAME` varchar(200) NOT NULL COMMENT '系列名',
  `USING_STATUS` varchar(32) NOT NULL COMMENT '在用状态',
  PRIMARY KEY (`ID`),
  KEY `I_CAR_MODEL__BRAND_ID` (`BRAND_ID`),
  KEY `I_CAR_MODEL__BRAND_NAME` (`BRAND_NAME`),
  KEY `I_CAR_MODEL__MODEL_ID` (`MODEL_ID`),
  KEY `I_CAR_MODEL__MODEL_NAME` (`MODEL_NAME`),
  KEY `I_CAR_MODEL__SERISE_ID` (`SERISE_ID`),
  KEY `I_CAR_MODEL__SERISE_NAME` (`SERISE_NAME`),
  KEY `I_CAR_MODEL__USING_STATUS` (`USING_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='车型表';



