-- DROP TABLE IF EXISTS `T_SYS_CAR_BRAND`;

CREATE TABLE `T_SYS_CAR_BRAND` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `BRAND_ID` text COMMENT '品牌ID',
  `BRAND_IMG` varchar(100) DEFAULT NULL COMMENT '品牌图片',
  `BRAND_NAME` varchar(50) NOT NULL COMMENT '品牌名',
  `CAPITAL` varchar(1) NOT NULL COMMENT '首字母',
  `USING_STATUS` varchar(32) NOT NULL COMMENT '在用状态',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='车品牌表';




