-- DROP TABLE IF EXISTS `T_SYS_CATEGORY`;

CREATE TABLE `T_SYS_CATEGORY` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `REMARKS` longtext COMMENT '备注',
  `USING_STATUS` varchar(32) NOT NULL COMMENT '在用状态',
  `CATEGORY_CODE` varchar(32) NOT NULL COMMENT '类目编号',
  `CATEGORY_NAME` varchar(200) NOT NULL COMMENT '类目名称',
  `CATEGORY_VALUE` varchar(200) NOT NULL COMMENT '类目值',
  `PARENT_CODE` varchar(32) NOT NULL COMMENT '父类目编号',
  PRIMARY KEY (`ID`),
  KEY `I_CATEGORY__CATEGORY_CODE` (`CATEGORY_CODE`),
  KEY `I_CATEGORY__CATEGORY_NAME` (`CATEGORY_NAME`),
  KEY `I_CATEGORY__PARENT_CODE` (`PARENT_CODE`),
  KEY `I_CATEGORY__USING_STATUS` (`USING_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='类目表';



