ALTER TABLE T_SYS_CATEGORY COMMENT='类目表';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN CATEGORY_CODE varchar(32) NOT NULL COMMENT '类目编号';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN CATEGORY_VALUE varchar(200) NOT NULL COMMENT '类目值';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN CATEGORY_NAME varchar(200) NOT NULL COMMENT '类目名称';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN PARENT_CODE varchar(32) NOT NULL COMMENT '父类目编号';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态';
ALTER TABLE T_SYS_CATEGORY MODIFY COLUMN REMARKS longtext COMMENT '备注';

CREATE INDEX I_CATEGORY__CATEGORY_CODE ON T_SYS_CATEGORY (CATEGORY_CODE);
CREATE INDEX I_CATEGORY__CATEGORY_NAME ON T_SYS_CATEGORY (CATEGORY_NAME);
CREATE INDEX I_CATEGORY__PARENT_CODE ON T_SYS_CATEGORY (PARENT_CODE);
CREATE INDEX I_CATEGORY__USING_STATUS ON T_SYS_CATEGORY (USING_STATUS);



