#database configurations
lichkin:
  framework:
    db:
      secondary:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/db_test
        username: root
        password: 