ALTER TABLE T_SYS_ROLE COMMENT='角色表';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN ROLE_NAME varchar(50) NOT NULL COMMENT '角色名称';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN DESCRIPTION varchar(100) NOT NULL COMMENT '描述';
ALTER TABLE T_SYS_ROLE MODIFY COLUMN SYSTEM_TAG varchar(100) NOT NULL COMMENT '系统标识';



