ALTER TABLE T_SYS_ROLE_MENU COMMENT='角色&菜单关联表';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN MENU_ID varchar(32) NOT NULL COMMENT '菜单ID';
ALTER TABLE T_SYS_ROLE_MENU MODIFY COLUMN ROLE_ID varchar(32) NOT NULL COMMENT '角色ID';

CREATE INDEX I_ROLE_MENU__USING_STATUS ON T_SYS_ROLE_MENU (USING_STATUS);
CREATE INDEX I_ROLE_MENU__INSERT_TIME ON T_SYS_ROLE_MENU (INSERT_TIME);
CREATE INDEX I_ROLE_MENU__MENU_ID ON T_SYS_ROLE_MENU (MENU_ID);
CREATE INDEX I_ROLE_MENU__ROLE_ID ON T_SYS_ROLE_MENU (ROLE_ID);



