ALTER TABLE T_SYS_APP_FEEDBACK COMMENT='客户端反馈表';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN REMARKS longtext NULL COMMENT '备注';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN APP_NAME varchar(50) NOT NULL COMMENT '客户端名称';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN CONTACT_WAY varchar(200) DEFAULT NULL COMMENT '联系方式';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN CURRENT_APP_VERSION varchar(10) NOT NULL COMMENT '当前版本，V1.0.0';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN FEEDBACK_FILE_IDS varchar(200) DEFAULT NULL COMMENT '反馈文件IDs';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN PLATFORM varchar(32) NOT NULL COMMENT '客户端类型';
ALTER TABLE T_SYS_APP_FEEDBACK MODIFY COLUMN USER_ID varchar(32) DEFAULT NULL COMMENT '用户ID';



