ALTER TABLE T_SYS_APP_VERSION COMMENT='客户端版本表';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN REMARKS longtext NULL COMMENT '备注';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN APP_NAME varchar(50) NOT NULL COMMENT '客户端名称';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN BRIEF varchar(100) NOT NULL COMMENT '新版本简介';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN CURRENT_APP_VERSION varchar(10) NOT NULL COMMENT '当前版本，V1.0.0';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN FORCE_UPDATE varchar(32) NOT NULL COMMENT '是否强制更新';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN PLATFORM varchar(32) NOT NULL COMMENT '客户端类型';
ALTER TABLE T_SYS_APP_VERSION MODIFY COLUMN URL varchar(100) DEFAULT NULL COMMENT '安卓客户端下载地址';



