ALTER TABLE T_SYS_SECURITY_CODE COMMENT='验证码表';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN BUS_TYPE varchar(20) NOT NULL COMMENT '业务类型(枚举)';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN CELLPHONE varchar(11) NOT NULL COMMENT '手机号码';
ALTER TABLE T_SYS_SECURITY_CODE MODIFY COLUMN SECURITY_CODE varchar(10) NOT NULL COMMENT '验证码';

CREATE INDEX I_SECURITY_CODE__INSERT_TIME ON T_SYS_SECURITY_CODE (INSERT_TIME);
CREATE INDEX I_SECURITY_CODE__USING_STATUS ON T_SYS_SECURITY_CODE (USING_STATUS);
CREATE INDEX I_SECURITY_CODE__BUS_TYPE ON T_SYS_SECURITY_CODE (BUS_TYPE);
CREATE INDEX I_SECURITY_CODE__CELLPHONE ON T_SYS_SECURITY_CODE (CELLPHONE);



