ALTER TABLE T_SYS_SMS COMMENT='短信表';
ALTER TABLE T_SYS_SMS MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_SMS MODIFY COLUMN CELLPHONE varchar(11) NOT NULL COMMENT '手机号码';
ALTER TABLE T_SYS_SMS MODIFY COLUMN MESSAGE varchar(255) NOT NULL COMMENT '短信内容';
ALTER TABLE T_SYS_SMS MODIFY COLUMN SEND_TIME varchar(19) NULL COMMENT '发送时间';

CREATE INDEX I_SMS__CELLPHONE ON T_SYS_SMS (CELLPHONE);
CREATE INDEX I_SMS__SEND_TIME ON T_SYS_SMS (SEND_TIME);



