ALTER TABLE T_SYS_OPER_LOG COMMENT='系统日志表';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN BUS_TYPE varchar(50) NOT NULL COMMENT '业务类型(枚举)';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN BUS_TYPE_NAME varchar(50) NOT NULL COMMENT '业务类型名称(枚举对应的中文)';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN OPER_LOGIN_ID varchar(32) NOT NULL COMMENT '操作人登录ID';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN OPER_TYPE varchar(10) NOT NULL COMMENT '操作类型(枚举)';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN OPER_USER_NAME varchar(50) NOT NULL COMMENT '操作人姓名';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN REMARKS longtext COMMENT '备注(可用于删除操作记录数据)';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN REQUEST_DATAS longtext NOT NULL COMMENT '请求数据';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN REQUEST_ID varchar(32) NOT NULL COMMENT '请求ID';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN REQUEST_IP varchar(32) NOT NULL COMMENT '请求IP';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN REQUEST_TIME varchar(20) NOT NULL COMMENT '请求时间';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN REQUEST_URL varchar(255) NOT NULL COMMENT '请求URL';
ALTER TABLE T_SYS_OPER_LOG MODIFY COLUMN SYSTEM_TAG varchar(100) NOT NULL COMMENT '系统标识';

CREATE INDEX I_OPER_LOG__BUS_TYPE ON T_SYS_OPER_LOG (BUS_TYPE);
CREATE INDEX I_OPER_LOG__OPER_TYPE ON T_SYS_OPER_LOG (OPER_TYPE);
CREATE INDEX I_OPER_LOG__REQUEST_ID ON T_SYS_OPER_LOG (REQUEST_ID);
CREATE INDEX I_OPER_LOG__REQUEST_IP ON T_SYS_OPER_LOG (REQUEST_IP);
CREATE INDEX I_OPER_LOG__REQUEST_TIME ON T_SYS_OPER_LOG (REQUEST_TIME);
CREATE INDEX I_OPER_LOG__REQUEST_URL ON T_SYS_OPER_LOG (REQUEST_URL);
CREATE INDEX I_OPER_LOG__SYSTEM_TAG ON T_SYS_OPER_LOG (SYSTEM_TAG);



