-- DROP TABLE IF EXISTS `T_SYS_OPER_LOG`;

CREATE TABLE `T_SYS_OPER_LOG` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `BUS_TYPE` varchar(50) NOT NULL COMMENT '业务类型(枚举)',
  `BUS_TYPE_NAME` varchar(50) NOT NULL COMMENT '业务类型名称(枚举对应的中文)',
  `OPER_LOGIN_ID` varchar(32) NOT NULL COMMENT '操作人登录ID',
  `OPER_TYPE` varchar(10) NOT NULL COMMENT '操作类型(枚举)',
  `OPER_USER_NAME` varchar(50) NOT NULL COMMENT '操作人姓名',
  `REMARKS` longtext COMMENT '备注(可用于删除操作记录数据)',
  `REQUEST_DATAS` longtext NOT NULL COMMENT '请求数据',
  `REQUEST_ID` varchar(32) NOT NULL COMMENT '请求ID',
  `REQUEST_IP` varchar(32) NOT NULL COMMENT '请求IP',
  `REQUEST_TIME` varchar(20) NOT NULL COMMENT '请求时间',
  `REQUEST_URL` varchar(255) NOT NULL COMMENT '请求URL',
  `SYSTEM_TAG` varchar(100) NOT NULL COMMENT '系统标识',
  PRIMARY KEY (`ID`),
  KEY `I_OPER_LOG__BUS_TYPE` (`BUS_TYPE`),
  KEY `I_OPER_LOG__OPER_TYPE` (`OPER_TYPE`),
  KEY `I_OPER_LOG__REQUEST_ID` (`REQUEST_ID`),
  KEY `I_OPER_LOG__REQUEST_IP` (`REQUEST_IP`),
  KEY `I_OPER_LOG__REQUEST_TIME` (`REQUEST_TIME`),
  KEY `I_OPER_LOG__REQUEST_URL` (`REQUEST_URL`),
  KEY `I_OPER_LOG__SYSTEM_TAG` (`SYSTEM_TAG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统日志表';



