ALTER TABLE T_SYS_AREA COMMENT='区域表';
ALTER TABLE T_SYS_AREA MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_AREA MODIFY COLUMN AREA_LEVEL varchar(32) NOT NULL COMMENT '区域等级';
ALTER TABLE T_SYS_AREA MODIFY COLUMN AREA_NAME varchar(100) NOT NULL COMMENT '区域名称';
ALTER TABLE T_SYS_AREA MODIFY COLUMN TELEPHONE_CODE varchar(6) DEFAULT NULL COMMENT '电话号码编码';
ALTER TABLE T_SYS_AREA MODIFY COLUMN USER_CARD_CODE varchar(6) NOT NULL COMMENT '身份证号码编码';




