ALTER TABLE T_SYS_NEWS COMMENT='新闻表';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN AUTHOR varchar(100) NULL COMMENT '作者';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN BANNER_FILE_ID varchar(32) NULL COMMENT '轮播图 (对应文件表id)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN BRIEF varchar(200) NULL COMMENT '简介';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN CATEGORY_CODE varchar(32) NULL COMMENT '分类(对应字典表ID)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN CONTENT longtext COMMENT '内容';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN LINK_URL varchar(200) NULL COMMENT '外链地址';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN NEWS_TITLE varchar(50) NULL COMMENT '标题';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN NEWS_TYPE varchar(20) NULL COMMENT '类型(枚举)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN THUMBNAIL_FILE_ID varchar(32) NULL COMMENT '缩略图(对应文件表id)';
ALTER TABLE T_SYS_NEWS MODIFY COLUMN SORT_NUM int(2) NULL COMMENT '轮播图序号';

CREATE INDEX I_NEWS__INSERT_TIME ON T_SYS_NEWS (INSERT_TIME);
CREATE INDEX I_NEWS__USING_STATUS ON T_SYS_NEWS (USING_STATUS);
CREATE INDEX I_NEWS__AUTHOR ON T_SYS_NEWS (AUTHOR);
CREATE INDEX I_NEWS__CATEGORY_CODE ON T_SYS_NEWS (CATEGORY_CODE);
CREATE INDEX I_NEWS__NEWS_TITLE ON T_SYS_NEWS (NEWS_TITLE);
CREATE INDEX I_NEWS__NEWS_TYPE ON T_SYS_NEWS (NEWS_TYPE);
CREATE INDEX I_NEWS__SORT_NUM ON T_SYS_NEWS (SORT_NUM);



