ALTER TABLE T_SYS_FTP COMMENT='文件表';
ALTER TABLE T_SYS_FTP MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_FTP MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_FTP MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_FTP MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_FTP MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_FTP MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_FTP MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_FTP MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_FTP MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_FTP MODIFY COLUMN EXT_NAME varchar(5) NOT NULL COMMENT '扩展名';
ALTER TABLE T_SYS_FTP MODIFY COLUMN FILE_FULL_NAME varchar(150) NOT NULL COMMENT '文件全名';
ALTER TABLE T_SYS_FTP MODIFY COLUMN FILE_NAME varchar(50) NOT NULL COMMENT '文件名';
ALTER TABLE T_SYS_FTP MODIFY COLUMN FILE_SIZE bigint(20) NOT NULL COMMENT '文件大小';
ALTER TABLE T_SYS_FTP MODIFY COLUMN MD5 varchar(32) NOT NULL COMMENT '文件MD5值';
ALTER TABLE T_SYS_FTP MODIFY COLUMN RELATIVE_PATH varchar(21) NOT NULL COMMENT '相对路径';
ALTER TABLE T_SYS_FTP MODIFY COLUMN ROOT_PATH varchar(25) NOT NULL COMMENT '根路径';
ALTER TABLE T_SYS_FTP MODIFY COLUMN SERVER_PATH varchar(50) NULL COMMENT 'FTP服务器地址';
ALTER TABLE T_SYS_FTP MODIFY COLUMN SHOW_NAME varchar(15) NOT NULL COMMENT '显示名';

CREATE INDEX I_FTP__USING_STATUS ON T_SYS_FTP (USING_STATUS);
CREATE INDEX I_FTP__INSERT_TIME ON T_SYS_FTP (INSERT_TIME);
CREATE INDEX I_FTP__EXT_NAME ON T_SYS_FTP (EXT_NAME);
CREATE INDEX I_FTP__MD5 ON T_SYS_FTP (MD5);
CREATE INDEX I_FTP__ROOT_PATH ON T_SYS_FTP (ROOT_PATH);
CREATE INDEX I_FTP__SERVER_PATH ON T_SYS_FTP (SERVER_PATH);



