ALTER TABLE T_SYS_USER_BANK_CARD COMMENT='人员银行卡表';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN ACTIVATE_DATE varchar(19) NULL COMMENT '激活时间';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN ALIAS varchar(50) NULL COMMENT '别名';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN BANK_ACCOUNT_NUM_MASK varchar(32) NULL COMMENT '银行卡号掩码';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN BANK_BRANCH varchar(100) NULL COMMENT '支行名称';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN BANK_CODE varchar(32) NULL COMMENT '银行编号';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN BANK_NAME varchar(100) NULL COMMENT '银行名称';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN BANKCARD_ID varchar(32) NULL COMMENT '银行卡绑定Id';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN BRANCH_NO varchar(32) NULL COMMENT '联行号';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CARD_ATTRIBUTE varchar(32) NULL COMMENT '卡属性';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CARD_SKIN varchar(32) NULL COMMENT '银行卡皮肤';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CARD_TYPE varchar(32) NULL COMMENT '卡类型';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CARD_VALID_DATE varchar(32) NULL COMMENT '卡验证时间';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CERT_NUM varchar(18) NULL COMMENT '证件号';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CERT_TYPE varchar(32) NULL COMMENT '证件类型';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CHANNEL_CODE varchar(32) NULL COMMENT '渠道编码';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CHECK_CODE varchar(32) NULL COMMENT '校验码';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN CITY varchar(32) NULL COMMENT '城市';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN EXTENTION varchar(200) NULL COMMENT '扩展信息';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN FINANCIAL_CARD varchar(50) NULL COMMENT '金融卡';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN IS_SIGNING varchar(32) NULL COMMENT '是否签约';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN IS_VERIFIED varchar(32) NULL COMMENT '是否认证';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN LOGIN_ID varchar(32) NOT NULL COMMENT '登录ID';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN MEMBER_ID varchar(32) NULL COMMENT '会员ID';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN MOBILE_NUM varchar(11) NULL COMMENT '手机号';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN PAY_ATTRIBUTE varchar(32) NULL COMMENT '支付属性';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN PROVINCE varchar(32) NULL COMMENT '省份';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN REAL_NAME varchar(50) NULL COMMENT '户名';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN STATUS varchar(32) NULL COMMENT '状态';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN UPDATE_TIME varchar(19) NULL COMMENT '更新时间';
ALTER TABLE T_SYS_USER_BANK_CARD MODIFY COLUMN USER_ID varchar(32) NOT NULL COMMENT '用户ID';

CREATE INDEX I_USER_BANK_CARD__USER_ID ON T_SYS_USER_BANK_CARD (USER_ID);
CREATE INDEX I_USER_BANK_CARD__LOGIN_ID ON T_SYS_USER_BANK_CARD (LOGIN_ID);
CREATE INDEX I_USER_BANK_CARD__REAL_NAME ON T_SYS_USER_BANK_CARD (REAL_NAME);
CREATE INDEX I_USER_BANK_CARD__MOBILE_NUM ON T_SYS_USER_BANK_CARD (MOBILE_NUM);
CREATE INDEX I_USER_BANK_CARD__CERT_NUM ON T_SYS_USER_BANK_CARD (CERT_NUM);



