-- DROP TABLE IF EXISTS `T_SYS_INTERFACES_REQUEST_LOG`;

CREATE TABLE `T_SYS_INTERFACES_REQUEST_LOG` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `CALLER_NAME` varchar(32) NOT NULL COMMENT '请求用户名',
  `PASSWORD` varchar(32) NOT NULL COMMENT '请求密码',
  `REQUEST_DATAS` longtext NOT NULL COMMENT '请求数据',
  `REQUEST_ID` varchar(32) NOT NULL COMMENT '请求ID',
  `REQUEST_IP` varchar(32) NOT NULL COMMENT '请求IP',
  `REQUEST_TIME` varchar(20) NOT NULL COMMENT '请求时间',
  `REQUEST_URL` varchar(255) NOT NULL COMMENT '请求URL',
  PRIMARY KEY (`ID`),
  KEY `I_INTERFACES_REQUEST_LOG__CALLER_NAME` (`CALLER_NAME`),
  KEY `I_INTERFACES_REQUEST_LOG__REQUEST_ID` (`REQUEST_ID`),
  KEY `I_INTERFACES_REQUEST_LOG__REQUEST_IP` (`REQUEST_IP`),
  KEY `I_INTERFACES_REQUEST_LOG__REQUEST_TIME` (`REQUEST_TIME`),
  KEY `I_INTERFACES_REQUEST_LOG__REQUEST_URL` (`REQUEST_URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='接口请求日志表';



