ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG COMMENT='接口请求日志表';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN CALLER_NAME varchar(32) NOT NULL COMMENT '请求用户名';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN PASSWORD varchar(32) NOT NULL COMMENT '请求密码';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN REQUEST_DATAS longtext NOT NULL COMMENT '请求数据';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN REQUEST_ID varchar(32) NOT NULL COMMENT '请求ID';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN REQUEST_IP varchar(32) NOT NULL COMMENT '请求IP';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN REQUEST_TIME varchar(20) NOT NULL COMMENT '请求时间';
ALTER TABLE T_SYS_INTERFACES_REQUEST_LOG MODIFY COLUMN REQUEST_URL varchar(255) NOT NULL COMMENT '请求URL';

CREATE INDEX I_INTERFACES_REQUEST_LOG__CALLER_NAME ON T_SYS_INTERFACES_REQUEST_LOG (CALLER_NAME);
CREATE INDEX I_INTERFACES_REQUEST_LOG__REQUEST_ID ON T_SYS_INTERFACES_REQUEST_LOG (REQUEST_ID);
CREATE INDEX I_INTERFACES_REQUEST_LOG__REQUEST_IP ON T_SYS_INTERFACES_REQUEST_LOG (REQUEST_IP);
CREATE INDEX I_INTERFACES_REQUEST_LOG__REQUEST_TIME ON T_SYS_INTERFACES_REQUEST_LOG (REQUEST_TIME);
CREATE INDEX I_INTERFACES_REQUEST_LOG__REQUEST_URL ON T_SYS_INTERFACES_REQUEST_LOG (REQUEST_URL);



