-- DROP TABLE IF EXISTS `T_SYS_INTERFACES_LOGIN`;

CREATE TABLE `T_SYS_INTERFACES_LOGIN` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `INTERFACES_VERSION` varchar(32) NOT NULL COMMENT '接口版本号',
  `LOGIN_NAME` varchar(32) NOT NULL COMMENT '接口请求用户名',
  `PWD` varchar(32) NOT NULL COMMENT '接口请求密码',
  `SYSTEM_TAG` varchar(50) NOT NULL COMMENT '系统标识',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='接口请求权限表';



