ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE COMMENT='管理员登录&角色关联表';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN REMARKS longtext NULL COMMENT '备注';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN LOGIN_ID varchar(32) NOT NULL COMMENT '登录ID';
ALTER TABLE T_SYS_ADMIN_LOGIN_ROLE MODIFY COLUMN ROLE_ID varchar(32) NOT NULL COMMENT '角色ID';

CREATE INDEX I_ADMIN_LOGIN_ROLE__USING_STATUS ON T_SYS_ADMIN_LOGIN_ROLE (USING_STATUS);
CREATE INDEX I_ADMIN_LOGIN_ROLE__INSERT_TIME ON T_SYS_ADMIN_LOGIN_ROLE (INSERT_TIME);
CREATE INDEX I_ADMIN_LOGIN_ROLE__LOGIN_ID ON T_SYS_ADMIN_LOGIN_ROLE (LOGIN_ID);
CREATE INDEX I_ADMIN_LOGIN_ROLE__ROLE_ID ON T_SYS_ADMIN_LOGIN_ROLE (ROLE_ID);



