ALTER TABLE T_SYS_ADMIN_LOGIN COMMENT='管理员登录表';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN REMARKS longtext NULL COMMENT '备注';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN BUS_ID varchar(50) NULL COMMENT '业务ID';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN CHECK_CODE varchar(32) NULL COMMENT '校验码';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN CELLPHONE varchar(11) NULL COMMENT '手机号码';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN EMAIL varchar(200) NULL COMMENT '电子邮箱';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN ERROR_TIMES tinyint(4) NULL COMMENT '密码错误次数';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN FIELD1 varchar(200) NULL COMMENT '备用字段';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN FIELD2 varchar(200) NULL COMMENT '备用字段';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN FIELD3 varchar(200) NULL COMMENT '备用字段';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN LOGIN_NAME varchar(32) NOT NULL COMMENT '登录名';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN PWD varchar(32) NOT NULL COMMENT '密码(MD5)';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN SECURITY_CODE varchar(10) NULL COMMENT '验证码';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN TOKEN varchar(32) NULL COMMENT '登录token';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN SYSTEM_TAG varchar(100) NOT NULL COMMENT '系统标识';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN USER_CARD varchar(64) NULL COMMENT '身份证号码';
ALTER TABLE T_SYS_ADMIN_LOGIN MODIFY COLUMN USER_ID varchar(32) NOT NULL COMMENT '人员ID';

CREATE INDEX I_ADMIN_LOGIN__USING_STATUS ON T_SYS_ADMIN_LOGIN (USING_STATUS);
CREATE INDEX I_ADMIN_LOGIN__INSERT_TIME ON T_SYS_ADMIN_LOGIN (INSERT_TIME);
CREATE INDEX I_ADMIN_LOGIN__BUS_ID ON T_SYS_ADMIN_LOGIN (BUS_ID);
CREATE INDEX I_ADMIN_LOGIN__USER_ID ON T_SYS_ADMIN_LOGIN (USER_ID);
CREATE INDEX I_ADMIN_LOGIN__CELLPHONE ON T_SYS_ADMIN_LOGIN (CELLPHONE);
CREATE INDEX I_ADMIN_LOGIN__EMAIL ON T_SYS_ADMIN_LOGIN (EMAIL);
CREATE INDEX I_ADMIN_LOGIN__USER_CARD ON T_SYS_ADMIN_LOGIN (USER_CARD);
CREATE INDEX I_ADMIN_LOGIN__LOGIN_NAME ON T_SYS_ADMIN_LOGIN (LOGIN_NAME);
CREATE INDEX I_ADMIN_LOGIN__SYSTEM_TAG ON T_SYS_ADMIN_LOGIN (SYSTEM_TAG);
CREATE INDEX I_ADMIN_LOGIN__TOKEN ON T_SYS_ADMIN_LOGIN (TOKEN);



