ALTER TABLE T_SYS_CAR_BRAND COMMENT='车品牌表';
ALTER TABLE T_SYS_CAR_BRAND MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_CAR_BRAND MODIFY COLUMN CAPITAL varchar(1) NOT NULL COMMENT '首字母';
ALTER TABLE T_SYS_CAR_BRAND MODIFY COLUMN BRAND_ID text NULL COMMENT '品牌ID';
ALTER TABLE T_SYS_CAR_BRAND MODIFY COLUMN BRAND_NAME varchar(50) NOT NULL COMMENT '品牌名';
ALTER TABLE T_SYS_CAR_BRAND MODIFY COLUMN BRAND_IMG varchar(100) NULL COMMENT '品牌图片';
ALTER TABLE T_SYS_CAR_BRAND MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态';



