ALTER TABLE T_SYS_CAR_MODEL COMMENT='车型表';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN ID varchar(64) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN BRAND_ID varchar(100) NOT NULL COMMENT '品牌ID';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN BRAND_NAME varchar(200) NOT NULL COMMENT '品牌名';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN DISPLACEMENT varchar(10) DEFAULT NULL COMMENT '排量';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN GUIDE_PRICE varchar(20) DEFAULT NULL COMMENT '指导价';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN MODEL_ID varchar(100) NOT NULL COMMENT '型号ID';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN MODEL_NAME varchar(200) NOT NULL COMMENT '型号名';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN PRODUCTION_STATE varchar(10) DEFAULT NULL COMMENT '生产状态（在产、停产）';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN PRODUCTION_WAY varchar(10) DEFAULT NULL COMMENT '生产方式（国产、合资、进口）';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN SALE_VERSION varchar(100) DEFAULT NULL COMMENT '销售版本';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN SALE_YEAR varchar(10) DEFAULT NULL COMMENT '销售年份';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN SERISE_ID varchar(100) NOT NULL COMMENT '系列ID';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN SERISE_NAME varchar(200) NOT NULL COMMENT '系列名';
ALTER TABLE T_SYS_CAR_MODEL MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态';

CREATE INDEX I_CAR_MODEL__BRAND_ID ON T_SYS_CAR_MODEL (BRAND_ID);
CREATE INDEX I_CAR_MODEL__BRAND_NAME ON T_SYS_CAR_MODEL (BRAND_NAME);
CREATE INDEX I_CAR_MODEL__MODEL_ID ON T_SYS_CAR_MODEL (MODEL_ID);
CREATE INDEX I_CAR_MODEL__MODEL_NAME ON T_SYS_CAR_MODEL (MODEL_NAME);
CREATE INDEX I_CAR_MODEL__SERISE_ID ON T_SYS_CAR_MODEL (SERISE_ID);
CREATE INDEX I_CAR_MODEL__SERISE_NAME ON T_SYS_CAR_MODEL (SERISE_NAME);
CREATE INDEX I_CAR_MODEL__USING_STATUS ON T_SYS_CAR_MODEL (USING_STATUS);



