ALTER TABLE T_SYS_USER_CAR COMMENT='用户车辆信息表';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN ID varchar(64) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN BRAND_ID text COMMENT '品牌ID';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN DEFAULT_CAR varchar(32) NOT NULL COMMENT '默认车辆（枚举）';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN ENGINE_NUMBER varchar(50) DEFAULT NULL COMMENT '发动机号';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN FRAME_NUMBER varchar(50) DEFAULT NULL COMMENT '车架号';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN LICENSE_PLATE_HEADER varchar(10) NOT NULL COMMENT '车牌号（省份码）';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN LICENSE_PLATE_NUMBER varchar(10) NOT NULL COMMENT '车牌号（号码）';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN MODEL_ID varchar(100) NOT NULL COMMENT '型号ID';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN SERISE_ID varchar(100) NOT NULL COMMENT '系列ID';
ALTER TABLE T_SYS_USER_CAR MODIFY COLUMN USER_ID varchar(32) NOT NULL COMMENT '用户ID';

CREATE INDEX I_USER_CAR__USER_ID ON T_SYS_USER_CAR (USER_ID);
CREATE INDEX I_USER_CAR__SERISE_ID ON T_SYS_USER_CAR (SERISE_ID);
CREATE INDEX I_USER_CAR__MODEL_ID ON T_SYS_USER_CAR (MODEL_ID);
CREATE INDEX I_USER_CAR__DEFAULT_CAR ON T_SYS_USER_CAR (DEFAULT_CAR);



