ALTER TABLE T_SYS_MAIL COMMENT='邮件表';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN ATTACHMENTS longtext NOT NULL COMMENT '附件列表';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN BCCS longtext NOT NULL COMMENT '暗送人列表';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN CCS longtext NOT NULL COMMENT '抄送人列表';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN CONTENT longtext NOT NULL COMMENT '邮件内容';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN FROM_ADDRESS varchar(100) NOT NULL COMMENT '发送人地址';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN SEND_TIME varchar(19) NOT NULL COMMENT '发送时间';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN SUBJECT varchar(100) NOT NULL COMMENT '邮件标题';
ALTER TABLE T_SYS_MAIL MODIFY COLUMN TOS longtext NOT NULL COMMENT '收件人列表';

CREATE INDEX I_MAIL__FROM_ADDRESS ON T_SYS_MAIL (FROM_ADDRESS);
CREATE INDEX I_MAIL__SEND_TIME ON T_SYS_MAIL (SEND_TIME);
CREATE INDEX I_MAIL__SUBJECT ON T_SYS_MAIL (SUBJECT);



