-- DROP TABLE IF EXISTS `T_SYS_SECURITY_CODE`;

CREATE TABLE `T_SYS_SECURITY_CODE` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `INSERT_LOGIN_ID` varchar(32) DEFAULT NULL COMMENT '新增操作人ID',
  `INSERT_SYSTEM_TAG` varchar(100) NOT NULL COMMENT '新增操作系统标识',
  `INSERT_TIME` varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)',
  `REMARKS` longtext COMMENT '备注',
  `UPDATE_LOGIN_ID` varchar(32) DEFAULT NULL COMMENT '更新操作人ID',
  `UPDATE_SYSTEM_TAG` varchar(100) NOT NULL COMMENT '更新操作系统标识',
  `UPDATE_TIME` varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)',
  `USING_STATUS` varchar(32) NOT NULL COMMENT '在用状态(枚举)',
  `BUS_TYPE` varchar(20) NOT NULL COMMENT '业务类型(枚举)',
  `CELLPHONE` varchar(11) NOT NULL COMMENT '手机号码',
  `SECURITY_CODE` varchar(10) NOT NULL COMMENT '验证码',
  PRIMARY KEY (`ID`),
  KEY `I_SECURITY_CODE__INSERT_TIME` (`INSERT_TIME`),
  KEY `I_SECURITY_CODE__USING_STATUS` (`USING_STATUS`),
  KEY `I_SECURITY_CODE__BUS_TYPE` (`BUS_TYPE`),
  KEY `I_SECURITY_CODE__CELLPHONE` (`CELLPHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='验证码表';



