ALTER TABLE T_SYS_WECHAT_MENU COMMENT='微信菜单表';
ALTER TABLE T_SYS_WECHAT_MENU MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_WECHAT_MENU MODIFY COLUMN BTN_NAME varchar(10) NOT NULL COMMENT '按钮名称';
ALTER TABLE T_SYS_WECHAT_MENU MODIFY COLUMN BTN_TYPE varchar(5) NOT NULL COMMENT '按钮类型';
ALTER TABLE T_SYS_WECHAT_MENU MODIFY COLUMN X tinyint(4) NOT NULL COMMENT '按钮位于菜单的横坐标';
ALTER TABLE T_SYS_WECHAT_MENU MODIFY COLUMN Y tinyint(4) NOT NULL COMMENT '按钮位于菜单的纵坐标';



