ALTER TABLE T_SYS_WECHAT_TOKEN COMMENT='微信access_token';
ALTER TABLE T_SYS_WECHAT_TOKEN MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_WECHAT_TOKEN MODIFY COLUMN ACCESS_TOKEN longtext NOT NULL COMMENT '微信全局唯一票据';
ALTER TABLE T_SYS_WECHAT_TOKEN MODIFY COLUMN EXPIRES_IN int(11) NOT NULL COMMENT '凭证有效时间';
ALTER TABLE T_SYS_WECHAT_TOKEN MODIFY COLUMN REQUEST_TIME varchar(19) NOT NULL COMMENT '获取凭证时间';
ALTER TABLE T_SYS_WECHAT_TOKEN MODIFY COLUMN TOKEN_TYPE tinyint(4) NOT NULL COMMENT '凭证类型。0:accessToken;1:jsapi_ticket;';



