ALTER TABLE T_SYS_MENU COMMENT='菜单表';
ALTER TABLE T_SYS_MENU MODIFY COLUMN ID varchar(32) NOT NULL COMMENT '主键';
ALTER TABLE T_SYS_MENU MODIFY COLUMN INSERT_LOGIN_ID varchar(32) NULL COMMENT '新增操作人ID';
ALTER TABLE T_SYS_MENU MODIFY COLUMN INSERT_SYSTEM_TAG varchar(100) NOT NULL COMMENT '新增操作系统标识';
ALTER TABLE T_SYS_MENU MODIFY COLUMN INSERT_TIME varchar(19) NOT NULL COMMENT '新增操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_MENU MODIFY COLUMN REMARKS longtext COMMENT '备注';
ALTER TABLE T_SYS_MENU MODIFY COLUMN UPDATE_LOGIN_ID varchar(32) NULL COMMENT '更新操作人ID';
ALTER TABLE T_SYS_MENU MODIFY COLUMN UPDATE_SYSTEM_TAG varchar(100) NOT NULL COMMENT '更新操作系统标识';
ALTER TABLE T_SYS_MENU MODIFY COLUMN UPDATE_TIME varchar(19) NOT NULL COMMENT '更新操作时间(yyyy-MM-dd HH:mm:ss)';
ALTER TABLE T_SYS_MENU MODIFY COLUMN USING_STATUS varchar(32) NOT NULL COMMENT '在用状态(枚举)';
ALTER TABLE T_SYS_MENU MODIFY COLUMN ICON varchar(50) NULL COMMENT '图标';
ALTER TABLE T_SYS_MENU MODIFY COLUMN MENU_CODE varchar(32) NOT NULL COMMENT '菜单编码';
ALTER TABLE T_SYS_MENU MODIFY COLUMN MENU_NAME varchar(50) NOT NULL COMMENT '菜单名称';
ALTER TABLE T_SYS_MENU MODIFY COLUMN ORDER_ID tinyint(4) NOT NULL COMMENT '排序号';
ALTER TABLE T_SYS_MENU MODIFY COLUMN PARENT_CODE varchar(32) NULL COMMENT '父菜单编码';
ALTER TABLE T_SYS_MENU MODIFY COLUMN SYSTEM_TAG varchar(100) NOT NULL COMMENT '系统标识';
ALTER TABLE T_SYS_MENU MODIFY COLUMN URL varchar(200) NULL COMMENT '菜单地址';
ALTER TABLE T_SYS_MENU MODIFY COLUMN ASSIGNABLE varchar(32) NULL COMMENT '是否可分配';



